api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "hub-price-transform"
type = "function"
uid = "6314a5a7-7b47-4142-a02e-695018350ecd"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
